version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
hooks:
  BeforeInstall:
    - location: scripts
      timeout: 300
      runas: root
      commands:
        - apt-get update
  ApplicationStop:
    - location: scripts
      timeout: 60
      runas: root
      commands:
        - service nginx stop
